### ISSUE TITLE
goiyov.io/ssl访问不了

### ISSUE THREAD

**Issue by autumn-ww** [nicecp/GoIyov#5]
goiyov.io/ssl访问不了，请问证书到哪去下载

**Comment by nicecp** [comment]
代理机要和手机在同一个局域网，手机WIFI链接需要手动设置为代理机的IP和端口，这样数据才能转发过来并安装上

PS：证书已经在项目里`cert/caRootCert.crt`，只是需要一个渠道把他安装到手机里，你可以用任意方式安装，比如放到webserver的根目录

**Comment by autumn-ww** [comment]
cert文件夹下面好像只有caRoot.crt没有caRootCert.crt

**Comment by nicecp** [comment]
这个文件是[安装生成书生成](https://github.com/nicecp/GoIyov/blob/master/cert/certificate.go#L206)的，完成后会删除。真正的[证书信息在这个位置](https://github.com/nicecp/GoIyov/blob/master/cert/certificate.go#L27)

**Comment by autumn-ww** [comment]
没仔细看。。谢谢了
